### ISSUE TITLE
Talk idea: Distributed transactions - Don’t do them! Also, this is how to do them

### ISSUE THREAD

**Issue by lachlankrautz** [brisbane-api-meetup/events#4]
How to make sure your transactions are still logically safe when parts of them happen in other services over the network.

**Comment by loklaan** [comment]
A generally good thing to know, past service dev! Keen.

**Comment by ababkov** [comment]
Can you put the word microservices in the talk?

**Comment by ababkov** [comment]
Thanks for the talk @lachlankrautz. I know it was a while ago now but could you post a link to the resources here when you get a sec?
