### ISSUE TITLE
Talk idea: 6 ways to an awesome API

### ISSUE THREAD

**Issue by AnnaGerber** [brisbane-api-meetup/events#5]
I gave this talk at BrisJS and would be happy to repeat it for this meetup.

Overview: This talk reflects on my journey from a  front-end focused fullstack web developer to dedicated API developer, and covers six strategies that you can apply to develop awesome APIs. 
About me: Anna is a senior backend Node.js developer at PCCW Global. 

(I'm also happy to prepare a new talk topic for this group but would need a bit more time to prepare - would not be ready in time for April).

**Comment by ababkov** [comment]
@AnnaGerber thanks will slot this one in - meet up should be third week of April will send out announcement soon.

**Comment by ababkov** [comment]
What's the approx length on this one?

**Comment by AnnaGerber** [comment]
It's around 20 - 25 minutes

**Comment by AnnaGerber** [comment]
Hi, I've been checking the meetup page but haven't seen any updates - any idea which day this meetup will be? I'm giving a talk on IoT at tech newbies on Wednesday the 18th so I hope this won't be the same night!

**Comment by ababkov** [comment]
Hey Amy,

Will be the week following - final day still tbc but will lock in soon.

**Comment by ababkov** [comment]
Ahh, sorry Anna!

**Comment by AnnaGerber** [comment]
ok, great thanks.

**Comment by ababkov** [comment]
Locked in for the 24th Anna, let me know if any issues: https://www.meetup.com/Brisbane-APIs-and-Microservices/events/249532570/

**Comment by ababkov** [comment]
@AnnaGerber thanks again for doing your talk at the last meetup. Could you throw a link to your slides up in the comments of https://www.meetup.com/Brisbane-APIs-and-Microservices/events/249532570/ if possible?
