### ISSUE TITLE
Talk Idea: API Gateways: Are they worth spending $5M of someone else's money on?

### ISSUE THREAD

**Issue by TrentBartlem** [brisbane-api-meetup/events#6]

**Comment by ababkov** [comment]
Thanks for submitting @TrentBartlem. Thoughts on length, (very) rough outline on this one?

**Comment by TrentBartlem** [comment]
* "It was at this moment, he knew...." aka when to recognise you have a problem that cannot be fixed with more of the same microservices
* "I like drawing boxes" aka what an API gateway does and where it sits in your architecture
* "Y Tho" aka what an API Gateway can do for you
* "Did you just reinvent a Service Bus?" aka no, but it's easy to get confused
* "Gateway All The Things" aka where it makes sense to have more than one, or in different parts of your multi-tier system
* "Nobody gets fired for buying IBM" aka who that major players are for commercial API gateways,  and whether you can get away with rolling your own

**Comment by ababkov** [comment]
Awesome - 20 or 40 minute talk?

**Comment by TrentBartlem** [comment]
I wouldn't expect a topic like that to hold anyone's interest for 40 minutes. Even 20 might be pushing it.

**Comment by ababkov** [comment]
Lightning talk (10 mins?)

**Comment by TrentBartlem** [comment]
Seems about right.

**Comment by ababkov** [comment]
Locked in for the Trent, let me know if any issues: https://www.meetup.com/Brisbane-APIs-and-Microservices/events/249532570/

**Comment by ababkov** [comment]
@TrentBartlem keen to do this one at the next meetup on 20 June? https://www.meetup.com/Brisbane-APIs-and-Microservices/events/250795186/

**Comment by ababkov** [comment]
@TrentBartlem we'll be running meetup later this month - are you keen to give this talk? Had a quick look at the outline, for my own interest would be curious to know if you've looked into kubernetes centric API gateways and / or open source alternatives - e.g. Ambassador, Kong. 

Anyway let me know if you're keen to give this talk a run.

**Comment by TrentBartlem** [comment]
I've looked into Apigee since the first draft of the presentation. The more gateways I look at, the less confident I am with my findings :/
