### ISSUE TITLE
Talk Idea: API Access Management Overview

### ISSUE THREAD

**Issue by ghost** [brisbane-api-meetup/events#7]
API Access Management Overview
- Access Management Challenges
- API Authorisation Options
- Benefits of a Centralised, Identity Driven Solution
- OpenID Connect and OAuth 2.0
- OAuth Scopes and Claims
- OAuth Flows

**Comment by ababkov** [comment]
Looks great @markcsmith1 - any idea on talk length: 10 / 20 / 40 mins?

**Comment by ghost** [comment]
I'm thinking it will take me 30 - 40 min ... but happy to make it fit any length of time.

**Comment by ghost** [comment]
Probably won't have time for a demo ... maybe leave that for a follow up presentation.

**Comment by ababkov** [comment]
40 mins it is

**Comment by ababkov** [comment]
Thanks for the talk @markcsmith1 :)
